# SPDX-FileCopyrightText: 2022 U Servers Comunicaciones, SC
# SPDX-License-Identifier: Apache-2.0

#defaultBaseImage: cgr.dev/chainguard/wolfi-base	
#defaultBaseImage: debian:11-slim
defaultBaseImage: debian:latest

#builds:
#  - id: miniprow
#    #dir: .
#    main: ./actions/broker/
#    env:
#      - CGO_ENABLED=0
#    flags:
#      - -trimpath
#    ldflags:
#      - -extldflags "-static"
#      - "{{ .Env.LDFLAGS }}"
