---
namespace: https://miniprow.io/
license: Apache-2.0
name: miniprow
creator:
    person: Puerco (adolfo.garcia@uservers.net)
artifacts:
    - type: directory
      source: .
      gomodules: true
    - type: file
      source: README.md
    - type: image
      source: ghcr.io/uservers/miniprow/miniprow:beta
      license: Apache-2.0
