name: build-image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: "what tag to use to build chainctl"
        type: string
        default: ""
        required: true

jobs:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1

      - uses: imjasonh/setup-ko@v0.6
        with:
          version: v0.12.0

      - name: Get current tag
        if: ${{ github.event_name != 'workflow_dispatch'}}
        run: echo "GIT_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Print info
        run: echo "TAG=${{ env.GIT_VERSION }} / Git Commit ${{ env.GIT_COMMIT }} - ${{ env.DOMAIN }}"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build container
        run: |
          ko build --bare ./actions/broker/ -t canary --platform=linux/amd64
        env:
          KO_DOCKER_REPO: ghcr.io/puerco/miniprow
