name: build-image

on:
  push:
    branches:
      - master
      - main
    #tags:
    #  - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: "tag to use"
        type: string
        default: ""
        required: false

jobs:
  setup:
    name: Build Container Image
    runs-on: ubuntu-latest
    #permissions:
      #packages: read/write
      #contents: read
    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.actor }}/miniprow
      TAG: ""

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1

      - uses: imjasonh/setup-ko@v0.6
        with:
          version: v0.12.0
      
      - name: Read Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Get Short Commit SHA
        run: |
          echo ${GITHUB_REF}
          echo "GIT_VERSION=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Print info
        run: echo "${{ env.GIT_VERSION }} / Git Commit ${{ env.GIT_COMMIT }} - ${{ env.DOMAIN }}"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Release
        if: ${{ env.TAG != '' }} && ${{ env.TAG != 'main' }} 
        run: |
          ko build --bare ./actions/broker/ -t latest -t ${{ env.TAG }} -t ${{ env.GIT_VERSION }} --platform=linux/amd64
        
      - name: Build Canary
        if: ${{ env.TAG == '' }}
        run: ko build --bare ./actions/broker/ -t canary -t ${{ env.GIT_VERSION }} --platform=linux/amd64
