name: build
#permissions:
#  contents: write
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - run: go build -o miniprow actions/broker/main.go
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: miniprow
          path: miniprow
          retention-days: 5 

