name: build
#permissions:
#  contents: write
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v3.1.0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.19.2'
      - run: go build -o miniprow actions/broker/main.go
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: miniprow
          path: miniprow
          retention-days: 5 

