name: provenance
on:
  workflow_run:
    types: [completed]
    workflows: [build]
jobs:
  attest:
    name: Attest Workflow Run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: puerco/provenance-action@a1d60342253e66ee52f322ab3085b40b7ac93ff6
    
