name: provenance
on:
  workflow_run:
    types: [completed]
    workflows: [build]
jobs:
  attest:
    name: Attest Workflow Run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: puerco/provenance-action@e438025742bdee8498e13a0228ce4c81afe20bbc
      with:
        GITHUB_TOKEN: ${{ secrets.MINIPROW_TOKEN }}


