name: "testing"
on:
  pull_request

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.5.4
      - uses: actions/setup-go@d60b41a563a30eac31c3ec623e6ff0b3f16e1a06 # v5.0.0
        with:
          go-version-file: go.mod
          cache: false
          check-latest: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v1.61
  gotest:
    name: go-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.5.4
      - name: go-test
        uses: actions/setup-go@d60b41a563a30eac31c3ec623e6ff0b3f16e1a06 # v5.0.0
        with:
          go-version-file: go.mod
          cache: false
          check-latest: true
      - run: go test ./... -cover

